# -*- coding: utf-8 -*-
"""Another copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fSyFQSs64bNUgkTk8RWro24T0SOHNYDC
"""

!pip install transformers

from transformers import GPT2Tokenizer,GPT2LMHeadModel

Tokenizer=GPT2Tokenizer.from_pretrained('gpt2-large')

model=GPT2LMHeadModel.from_pretrained('gpt2-large',pad_token_id=Tokenizer.eos_token_id)

Tokenizer.eos_token_id

Tokenizer.decode(Tokenizer.eos_token_id)

sentence='I love travelling'
numeric_ids=Tokenizer.encode(sentence,return_tensors='pt')

numeric_ids

Tokenizer.decode(numeric_ids[0][2])

Result=model.generate(numeric_ids,max_length=100,num_beams=5,no_repeat_ngram_size=2,early_stopping=True)

Result

Generated_text=Tokenizer.decode(Result[0],skip_special_tokens=True)
print(Generated_text)

